server:
    port: 9090 

spring:
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:file:~/template_db
        username: root
        password: root
        hikari:
            minimum-idle: 1
            maximum-pool-size: 5
            connection-test-query: SELECT 1 
        
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
    h2:
        console:
            enabled: true
    jackson:
        serialization:
            fail-on-empty-beans: false
            write-dates-as-timestamps: false
        deserialization:
            fail-on-unknown-properties: false
        date-format: yyyy-MM-dd
    flyway:
        baseline-on-migrate: true
        validate-on-migrate: false
        url: jdbc:h2:file:~/template_db
        user: root
        password: root